# Generated by Django 4.2.2 on 2023-07-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hostel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='available_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bedspace', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=1000)),
                ('facilities', models.CharField(blank=True, choices=[('tv', 'TV'), ('fridge', 'Fridge'), ('air_condition', 'Air Condition'), ('bathroom', 'Bathroom'), ('study_desk', 'Study Desk'), ('wardrobe', 'Wardrobe')], max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
    ]
