# Generated by Django 4.2.2 on 2023-07-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_room_availability_room_number_available_and_more'),
    ]

    operations = [
    ]
