# Generated by Django 4.2.2 on 2023-07-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_auto_20230719_1654'),
    ]

    operations = [
    ]
