# Generated by Django 4.2.2 on 2023-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_facility_remove_room_facilities_room_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
