# Generated by Django 4.2.2 on 2023-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='available_rooms',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default=False, max_length=1000),
            preserve_default=False,
        ),
    ]
