# Generated by Django 4.2.2 on 2023-07-22 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_rename_facility_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='rating',
            field=models.FloatField(blank=True, default=2.5, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
