# Generated by Django 4.2.2 on 2023-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_hostel_hostel_img_url_room_room_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img_url',
            field=models.CharField(blank=True, default='https://rnb.scene7.com/is/image/roomandboard/MHH_Liv_ES1021_0523?size=900,900&scl=1', max_length=200),
        ),
    ]
