# Generated by Django 4.2.2 on 2023-08-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_alter_room_room_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
