# Generated by Django 4.2.2 on 2023-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_hguest_check_in_date_hguest_check_out_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hguest',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hguest',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hguest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hguest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hguest',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
