# Generated by Django 4.2.2 on 2023-07-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_remove_hguest_is_verified_hmanager_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hguest',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.AlterModelOptions(
            name='hmanager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
