# Generated by Django 4.2.2 on 2023-07-28 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_hostel_hostel_img_url_room_room_img_url'),
        ('usermanagement', '0006_alter_hguest_options_alter_hmanager_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rooms', models.ManyToManyField(related_name='collections', to='hostel.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hguest',
            name='collections',
            field=models.ManyToManyField(related_name='users', to='usermanagement.collection'),
        ),
    ]
