# Generated by Django 4.2.2 on 2023-07-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_collection_hguest_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(default='first_collection', max_length=125),
            preserve_default=False,
        ),
    ]
