# Generated by Django 4.2.2 on 2023-08-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hguest',
            name='special_requests',
        ),
    ]
