# Generated by Django 4.2.2 on 2023-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_remove_hguest_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hguest',
            name='collections',
            field=models.ManyToManyField(related_name='collected_by', to='usermanagement.collection'),
        ),
    ]
